Upgrade to IPFS 0.27
ipfs-shipyard/peerpad-core pull request #6
Opened 2017-12-04 11:35 UTC by pgte

- [x] Use to websocket-star (instead of webrtc-star) transport
- [x] Migrate repo version
- [ ] Test

2017-12-04 12:06 UTC, pgte commented
Currently running into this issue: https://github.com/libp2p/js-libp2p-websocket-star/issues/34

2017-12-05 21:09 UTC, daviddias requested changes

2017-12-05 21:09 UTC, daviddias commented on src/backend/ipfs.js
> +            '/dns4/ws-star-signal-1.servep2p.com/tcp/443/wss/p2p-websocket-star'
Why the change??

2017-12-05 22:12 UTC, pgte commented on src/backend/ipfs.js
> +            '/dns4/ws-star-signal-1.servep2p.com/tcp/443/wss/p2p-websocket-star'
Switched because this was the recommended rendez-vous server address on the docs..

2017-12-05 22:16 UTC, pgte commented on src/backend/ipfs.js
> +            '/dns4/ws-star-signal-1.servep2p.com/tcp/443/wss/p2p-websocket-star'
We should eventually switch to a peerpad-specific one..

2017-12-05 22:21 UTC, diasdavid commented on src/backend/ipfs.js
> +            '/dns4/ws-star-signal-1.servep2p.com/tcp/443/wss/p2p-websocket-star'
Good point, missed updating there https://github.com/libp2p/js-libp2p-websocket-star/pull/40

2017-12-05 22:21 UTC, diasdavid commented on src/backend/ipfs.js
> +            '/dns4/ws-star-signal-1.servep2p.com/tcp/443/wss/p2p-websocket-star'
I believed people would use https://github.com/ipfs/js-ipfs#is-there-a-more-stable-alternative-to-webrtc-star-that-offers-a-similar-functionality for reference

2017-12-06 08:51 UTC, daviddias approved these changes

2017-12-06 08:53 UTC, diasdavid commented
@pgte can you break this PR into two?
- Upgrade to js-ipfs 0.27 (continue to use webrtc-star)
- Move away from webrtc-star and use websocket-star

There are some significant perf improvements in 0.27 that you might want to start using right away

2017-12-06 08:54 UTC, daviddias requested changes

2017-12-06 08:54 UTC, diasdavid commented on package.json
> +    "ipfs": "^0.27.0",
Better change this to `~ `

2017-12-06 18:57 UTC, daviddias requested changes

2017-12-06 18:57 UTC, diasdavid commented on src/backend/index.js
> +>>>>>>> error handling and upgraded to IPFS 0.27 files API
merge conflict

2017-12-07 21:12 UTC, merged